package Vista;

import Modelo.Cancion;
import Modelo.CancionDAO;
import Modelo.Cancion_vinilo;
import Modelo.Cancion_viniloDAO;
import Modelo.Disco_mp3;
import Modelo.Disco_mp3DAO;
import Modelo.Disco_vinilo;
import Modelo.Disco_viniloDAO;
import Modelo.Sesion;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AsociarCanciones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AsociarCanciones.class.getName());

    public AsociarCanciones() {
        initComponents();
        ocultarComponentes();
        // Dejar el JList vacío
        jLista.setModel(new javax.swing.DefaultListModel<>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbVendedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAnadirCancion = new javax.swing.JButton();
        imgSalir = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        lbVendedor1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscarV = new javax.swing.JButton();
        imgDisco = new javax.swing.JLabel();
        LNom = new javax.swing.JLabel();
        jlnombre = new javax.swing.JLabel();
        jlautor = new javax.swing.JLabel();
        jlimagen = new javax.swing.JLabel();
        LAutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        lbdiscomp3 = new javax.swing.JLabel();
        jlcan = new javax.swing.JLabel();
        btnBuscarM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        lbVendedor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbVendedor.setText("Asociar canciones existentes");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        btnAnadirCancion.setBackground(new java.awt.Color(204, 204, 204));
        btnAnadirCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAnadirCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mas 15px.png"))); // NOI18N
        btnAnadirCancion.setText("Agregar canción");
        btnAnadirCancion.addActionListener(this::btnAnadirCancionActionPerformed);

        imgSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo salir.png"))); // NOI18N
        imgSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalirMouseClicked(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID canción", "Autor", "Nombre", "Género", "duración"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        lbVendedor1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor1.setText("Digite el ID del disco creado:");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBuscarV.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa 15px.png"))); // NOI18N
        btnBuscarV.setText("Buscar vinilo");
        btnBuscarV.addActionListener(this::btnBuscarVActionPerformed);

        LNom.setText("texto");

        jlnombre.setText("Nombre del disco:");

        jlautor.setText("Autor:");

        jlimagen.setText("Imagen:");

        LAutor.setText("texto");

        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLista);

        lbdiscomp3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbdiscomp3.setText("texto");

        jlcan.setText("Canciones:");

        btnBuscarM.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa 15px.png"))); // NOI18N
        btnBuscarM.setText("Buscar Mp3");
        btnBuscarM.addActionListener(this::btnBuscarMActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVendedor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarV, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlimagen)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlautor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlcan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbdiscomp3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jlnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNom, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgSalir)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(btnAnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbVendedor)
                    .addComponent(imgSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarV)
                    .addComponent(btnBuscarM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lbdiscomp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlimagen)
                    .addComponent(jlnombre)
                    .addComponent(LNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlautor)
                            .addComponent(LAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlcan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnadirCancion)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocultarComponentes() {
        LNom.setVisible(false);
        LAutor.setVisible(false);
        lbdiscomp3.setVisible(false);
        jlimagen.setVisible(false);
        jlnombre.setVisible(false);
        jlautor.setVisible(false);
        jlcan.setVisible(false);

        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);

        btnAnadirCancion.setVisible(false);

    }

    private void mostrarComponentes() {
        LNom.setVisible(true);
        LAutor.setVisible(true);
        lbdiscomp3.setVisible(true);
        jlimagen.setVisible(true);
        jlnombre.setVisible(true);
        jlautor.setVisible(true);
        jlcan.setVisible(true);

        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(true);
        btnAnadirCancion.setVisible(true);
    }

    private void cargarCancionesDelDisco(int idDisco) {
        Cancion_viniloDAO cavD = new Cancion_viniloDAO();
        List<Cancion> lista = cavD.listarCancionesPorDisco(idDisco);

        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();

        for (Cancion c : lista) {
            modelo.addElement(c.getNombre() + " - " + c.getDuracion());
        }

        jLista.setModel(modelo);
    }


    private void btnAnadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirCancionActionPerformed
        // ================================
        // 1. Validar id del disco
        // ================================
        String idTexto = txtId.getText().trim();
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe buscar un disco primero.");
            return;
        }

        int idDisco;
        try {
            idDisco = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
            return;
        }

        // ================================
        // 2. Verificar selección de canción
        // ================================
        int fila = jTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una canción de la tabla.");
            return;
        }

        int idCancion = Integer.parseInt(jTable.getValueAt(fila, 0).toString());

        // ================================
        // 3. Saber si el disco es vinilo o mp3
        // ================================
        String tipoDisco = lbdiscomp3.getText(); // VINILO o MP3

        // ================================
        // 4. Crear objeto de relación
        // ================================
        Cancion_vinilo cav = new Cancion_vinilo();
        cav.setId_cancion(idCancion);
        cav.setId_disco_vinilo(idDisco);

        Cancion_viniloDAO cavD = new Cancion_viniloDAO();

        // ================================
        // 5. Registrar en la relación
        // ================================
        boolean ok = cavD.agregarCancionAVinilo(cav);

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Canción agregada correctamente al " + tipoDisco);
            cargarCancionesDelDisco(idDisco);  //  <<–– actualiza jLista
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo agregar la canción.");
        }
    }//GEN-LAST:event_btnAnadirCancionActionPerformed

    private void imgSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalirMouseClicked
        AgregarProducto prod = new AgregarProducto();
        prod.setVisible(true);
        prod.setLocationRelativeTo(null);
        prod.setResizable(false);
        dispose();
    }//GEN-LAST:event_imgSalirMouseClicked

    private void cargarCancionesEnTabla() {
        int idVendedor = Sesion.getIdVendedor();

        CancionDAO caD = new CancionDAO();
        List<Cancion> lista = caD.listarCancionesPorVendedor(idVendedor);

        String[] columnas = {"ID canción", "Autor", "Nombre", "Género", "Duración"};

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

        for (Cancion c : lista) {
            modelo.addRow(new Object[]{
                c.getId_cancion(),
                c.getAutorNombre(),
                c.getNombre(),
                c.getGenero(),
                c.getDuracion()
            });
        }

        jTable.setModel(modelo);
    }

    private void cargarImagen(byte[] imgBytes) {

        if (imgBytes != null && imgBytes.length > 0) {

            ImageIcon icon = new ImageIcon(imgBytes);
            Image img = icon.getImage().getScaledInstance(
                    imgDisco.getWidth(),
                    imgDisco.getHeight(),
                    Image.SCALE_SMOOTH
            );
            imgDisco.setIcon(new ImageIcon(img));

        } else {
            // Imagen por defecto desde carpeta img
            ImageIcon iconDefault = new ImageIcon(
                    getClass().getResource("/img/disco.png")
            );

            Image imgDefault = iconDefault.getImage().getScaledInstance(
                    imgDisco.getWidth(),
                    imgDisco.getHeight(),
                    Image.SCALE_SMOOTH
            );

            imgDisco.setIcon(new ImageIcon(imgDefault));
        }
    }

    private void mostrarVinilo(Disco_vinilo dv) {

        lbdiscomp3.setText("VINILO");
        LNom.setText(dv.getNombre());
        LAutor.setText(dv.getAutorNombre());

        cargarImagen(dv.getImagen());

        mostrarComponentes();
        cargarCancionesEnTabla();
        cargarCancionesDelDisco(dv.getId_disco_vinilo());
    }

    private void mostrarMp3(Disco_mp3 dm) {

        lbdiscomp3.setText("MP3");
        LNom.setText(dm.getNombre());
        LAutor.setText(dm.getAutorNombre());

        cargarImagen(dm.getImagen());

        mostrarComponentes();
        cargarCancionesEnTabla();
    }


    private void btnBuscarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVActionPerformed
        String idTexto = txtId.getText().trim();

        // ==== Validar campo vacío ====
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de disco.");
            return;
        }
        try {
            int id = Integer.parseInt(idTexto);

            Disco_viniloDAO dvD = new Disco_viniloDAO();
            Disco_vinilo dv = dvD.buscarPorIdV(id);

            // ============================
            //    1. NO EXISTE VINILO
            // ============================
            if (dv == null) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this, "No existe un disco con ese ID.");
                return;
            }

            // ============================
            //    2. VALIDAR QUE EL DISCO
            //       PERTENECE AL VENDEDOR
            // ============================
            int idUsuarioActual = Sesion.getIdVendedor();

            if (dv.getId_vendedor() != idUsuarioActual) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this,
                        "No puede modificar este disco porque pertenece a otro vendedor.");
                return;
            }

            // ============================
            //    3. MOSTRAR VINILO
            // ============================
            mostrarVinilo(dv);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
        }
    }//GEN-LAST:event_btnBuscarVActionPerformed

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        String idTexto = txtId.getText().trim();

        // ==== Validar campo vacío ====
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de disco.");
            return;
        }
        try {
            int id = Integer.parseInt(idTexto);

            Disco_mp3DAO dmD = new Disco_mp3DAO();
            Disco_mp3 dm = dmD.buscarPorIM(id);

            // ============================
            //    1. NO EXISTE MP3
            // ============================
            if (dm == null) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this, "No existe un disco con ese ID.");
                return;
            }

            // ============================
            //    2. VALIDAR QUE EL DISCO
            //       PERTENECE AL VENDEDOR
            // ============================
            int idUsuarioActual = Sesion.getIdVendedor();

            if (dm.getId_vendedor() != idUsuarioActual) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this,
                        "No puede modificar este disco porque pertenece a otro vendedor.");
                return;
            }

            // ============================
            //    3. MOSTRAR MP3
            // ============================
            mostrarMp3(dm);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
        }
    }//GEN-LAST:event_btnBuscarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AsociarCanciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAutor;
    private javax.swing.JLabel LNom;
    private javax.swing.JButton btnAnadirCancion;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnBuscarV;
    private javax.swing.JLabel imgDisco;
    private javax.swing.JLabel imgSalir;
    private javax.swing.JList<String> jLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jlautor;
    private javax.swing.JLabel jlcan;
    private javax.swing.JLabel jlimagen;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor1;
    private javax.swing.JLabel lbdiscomp3;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
