package Vista;

import Modelo.Cancion;
import Modelo.CancionDAO;
import Modelo.Cancion_disco_mp3;
import Modelo.Cancion_disco_mp3DAO;
import Modelo.Cancion_vinilo;
import Modelo.Cancion_viniloDAO;
import Modelo.Disco_mp3;
import Modelo.Disco_mp3DAO;
import Modelo.Disco_vinilo;
import Modelo.Disco_viniloDAO;
import Modelo.Sesion;
import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

public class AsociarCanciones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AsociarCanciones.class.getName());

    public AsociarCanciones() {
        initComponents();
        ocultarComponentes();
        // Dejar el JList vacío
        jLista.setModel(new javax.swing.DefaultListModel<>());
        // Cursor tipo mano en el label de salir
        imgSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Cursor tipo mano en el botón buscar vinilo
        btnBuscarV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarV.setText("<html><center>Buscar<br>Vinilo</center></html>");
        // Cursor tipo mano en el botón buscar mp3
        btnBuscarM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarM.setText("<html><center>Buscar<br>MP3</center></html>");
        // Cursor tipo mano en el botón añadir cancion
        btnAnadirCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Cursor tipo mano en el botón añadir cancion
        btnBorrarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarCancion.setText("<html><center>Borrar<br>Canción</center></html>");

        // COLOR DE FONDO PARA EL HEADER
        javax.swing.table.JTableHeader header = jTable.getTableHeader();
        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                jTable.getTableHeader().setBackground(new java.awt.Color(89, 89, 89));

                jScrollPane2.getViewport().setBackground(new java.awt.Color(89, 89, 89));
                c.setBackground(new java.awt.Color(89, 89, 89));
                c.setForeground(Color.WHITE);
                setHorizontalAlignment(CENTER);
                return c;
            }
        });

        // MOSTRAR EL BOTON PARA BORRAR LA CANCION DE LA LISTA
        jLista.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                if (jLista.getSelectedIndex() != -1) {
                    btnBorrarCancion.setVisible(true);
                } else {
                    btnBorrarCancion.setVisible(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbVendedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAnadirCancion = new javax.swing.JButton();
        imgSalir = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        lbVendedor1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscarV = new javax.swing.JButton();
        imgDisco = new javax.swing.JLabel();
        LNom = new javax.swing.JLabel();
        jlnombre = new javax.swing.JLabel();
        jlautor = new javax.swing.JLabel();
        jlimagen = new javax.swing.JLabel();
        LAutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        lbdiscomp3 = new javax.swing.JLabel();
        jlcan = new javax.swing.JLabel();
        btnBuscarM = new javax.swing.JButton();
        lbtitulo2 = new javax.swing.JLabel();
        btnBorrarCancion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        lbVendedor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbVendedor.setText("Asociar canciones existentes");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        btnAnadirCancion.setBackground(new java.awt.Color(204, 204, 204));
        btnAnadirCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAnadirCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mas 15px.png"))); // NOI18N
        btnAnadirCancion.setText("Agregar canción");
        btnAnadirCancion.addActionListener(this::btnAnadirCancionActionPerformed);

        imgSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo salir.png"))); // NOI18N
        imgSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalirMouseClicked(evt);
            }
        });

        jTable.setBackground(new java.awt.Color(89, 89, 89));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID canción", "Autor", "Nombre", "Género", "duración"
            }
        ));
        jTable.setGridColor(new java.awt.Color(89, 89, 89));
        jTable.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(jTable);

        lbVendedor1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor1.setText("Digite el ID del disco creado:");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnBuscarV.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa 15px.png"))); // NOI18N
        btnBuscarV.setText("Buscar vinilo");
        btnBuscarV.addActionListener(this::btnBuscarVActionPerformed);

        LNom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LNom.setText("texto");

        jlnombre.setText("Nombre del disco:");

        jlautor.setText("Autor:");

        jlimagen.setText("Imagen:");

        LAutor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LAutor.setText("texto");

        jLista.setBackground(new java.awt.Color(89, 89, 89));
        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jLista.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jLista);

        lbdiscomp3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbdiscomp3.setText("texto");

        jlcan.setText("Canciones:");

        btnBuscarM.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa 15px.png"))); // NOI18N
        btnBuscarM.setText("Buscar Mp3");
        btnBuscarM.addActionListener(this::btnBuscarMActionPerformed);

        lbtitulo2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbtitulo2.setText("Canciones disponibles para agregar");

        btnBorrarCancion.setBackground(new java.awt.Color(204, 204, 204));
        btnBorrarCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBorrarCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/borrar.png"))); // NOI18N
        btnBorrarCancion.setText("Borrar Canción");
        btnBorrarCancion.addActionListener(this::btnBorrarCancionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVendedor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarV, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlimagen)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlcan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnBorrarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jlautor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lbdiscomp3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtitulo2))))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jlnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNom, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgSalir)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnAnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbVendedor)
                    .addComponent(imgSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbVendedor1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbdiscomp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlimagen)
                    .addComponent(jlnombre)
                    .addComponent(LNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlautor)
                            .addComponent(LAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlcan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBorrarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                    .addComponent(imgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lbtitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnadirCancion)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocultarComponentes() {
        LNom.setVisible(false);
        LAutor.setVisible(false);
        lbdiscomp3.setVisible(false);
        jlimagen.setVisible(false);
        jlnombre.setVisible(false);
        jlautor.setVisible(false);
        jlcan.setVisible(false);
        lbtitulo2.setVisible(false);

        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);

        btnAnadirCancion.setVisible(false);
        btnBorrarCancion.setVisible(false);

    }

    private void mostrarComponentes() {
        LNom.setVisible(true);
        LAutor.setVisible(true);
        lbdiscomp3.setVisible(true);
        jlimagen.setVisible(true);
        jlnombre.setVisible(true);
        jlautor.setVisible(true);
        jlcan.setVisible(true);
        lbtitulo2.setVisible(true);

        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(true);
        btnAnadirCancion.setVisible(true);
    }

    private void cargarCancionesDelVinilo(int idVinilo) {
        Cancion_viniloDAO cavD = new Cancion_viniloDAO();
        List<Cancion> lista = cavD.listarCancionesPorVinilo(idVinilo);

        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();

        for (Cancion c : lista) {
            modelo.addElement(
                    c.getId_cancion() + " - " + c.getNombre() + " - " + c.getDuracion()
            );
        }

        jLista.setModel(modelo);
    }

    private void cargarCancionesDelMp3(int idMp3) {
        Cancion_disco_mp3DAO camD = new Cancion_disco_mp3DAO();
        List<Cancion> lista = camD.listarCancionesPorMp3(idMp3);

        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();

        for (Cancion c : lista) {
            modelo.addElement(
                    c.getId_cancion() + " - " + c.getNombre() + " - " + c.getDuracion()
            );
        }

        jLista.setModel(modelo);
    }


    private void btnAnadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirCancionActionPerformed
        // ================================
        // 1. Validar id del disco
        // ================================
        String idTexto = txtId.getText().trim();
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe buscar un disco primero.");
            return;
        }

        int idDisco;
        try {
            idDisco = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
            return;
        }

        // ================================
        // 2. Verificar selección de canción
        // ================================
        int fila = jTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una canción de la tabla.");
            return;
        }

        int idCancion = Integer.parseInt(jTable.getValueAt(fila, 0).toString());

        // ================================
        // 3. Saber si es VINILO o MP3
        // ================================
        String tipoDisco = lbdiscomp3.getText(); // VINILO o MP3

        boolean ok = false;

        if (tipoDisco.equalsIgnoreCase("VINILO")) {

            // ================================
            // 4. Agregar a cancion_vinilo
            // ================================
            Cancion_vinilo cav = new Cancion_vinilo();
            cav.setId_cancion(idCancion);
            cav.setId_disco_vinilo(idDisco);

            Cancion_viniloDAO cavD = new Cancion_viniloDAO();
            // Verificar si ya existe
            if (cavD.existeCancionEnVinilo(idDisco, idCancion)) {
                JOptionPane.showMessageDialog(this, "Esta canción ya está asociada a este vinilo.");
                return;
            }

            ok = cavD.agregarCancionAVinilo(cav);

            if (ok) {
                cargarCancionesDelVinilo(idDisco);
            }

        } else if (tipoDisco.equalsIgnoreCase("MP3")) {

            // ================================
            // 5. Agregar a disco_cancion
            // ================================
            Cancion_disco_mp3 cmp3 = new Cancion_disco_mp3();
            cmp3.setId_cancion(idCancion);
            cmp3.setId_disco_mp3(idDisco);

            Cancion_disco_mp3DAO cmp3D = new Cancion_disco_mp3DAO();
            // Verificar si ya existe
            if (cmp3D.existeCancionEnMp3(idDisco, idCancion)) {
                JOptionPane.showMessageDialog(this, "Esta canción ya está asociada a este MP3.");
                return;
            }

            ok = cmp3D.agregarCancionAMp3(cmp3);

            if (ok) {
                cargarCancionesDelMp3(idDisco);
            }
        }

        // ================================
        // 6. Mensaje final
        // ================================
        if (ok) {
            JOptionPane.showMessageDialog(this, "Canción agregada correctamente al " + tipoDisco);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar la canción.");
        }
    }//GEN-LAST:event_btnAnadirCancionActionPerformed

    private void imgSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalirMouseClicked

        AgregarProducto ap = new AgregarProducto();
        ap.setVisible(true);
        ap.setVisible(true);
        ap.setLocationRelativeTo(null);
        ap.setResizable(false);
        dispose();
    }//GEN-LAST:event_imgSalirMouseClicked

    private void cargarCancionesEnTabla() {
        int idVendedor = Sesion.getIdVendedor();

        CancionDAO caD = new CancionDAO();
        List<Cancion> lista = caD.listarCancionesPorVendedor(idVendedor);

        String[] columnas = {"ID canción", "Autor", "Nombre", "Género", "Duración"};

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

        for (Cancion c : lista) {
            modelo.addRow(new Object[]{
                c.getId_cancion(),
                c.getAutorNombre(),
                c.getNombre(),
                c.getGenero(),
                c.getDuracion()
            });
        }

        jTable.setModel(modelo);
    }

    private void cargarImagen(byte[] imgBytes) {

        if (imgBytes != null && imgBytes.length > 0) {

            ImageIcon icon = new ImageIcon(imgBytes);
            Image img = icon.getImage().getScaledInstance(
                    imgDisco.getWidth(),
                    imgDisco.getHeight(),
                    Image.SCALE_SMOOTH
            );
            imgDisco.setIcon(new ImageIcon(img));

        } else {
            // Imagen por defecto desde carpeta img
            ImageIcon iconDefault = new ImageIcon(
                    getClass().getResource("/img/disco.png")
            );

            Image imgDefault = iconDefault.getImage().getScaledInstance(
                    imgDisco.getWidth(),
                    imgDisco.getHeight(),
                    Image.SCALE_SMOOTH
            );

            imgDisco.setIcon(new ImageIcon(imgDefault));
        }
    }

    private void mostrarVinilo(Disco_vinilo dv) {

        lbdiscomp3.setText("VINILO");
        LNom.setText(dv.getNombre());
        LAutor.setText(dv.getAutorNombre());

        cargarImagen(dv.getImagen());

        mostrarComponentes();
        cargarCancionesEnTabla();
        cargarCancionesDelVinilo(dv.getId_disco_vinilo());
    }

    private void mostrarMp3(Disco_mp3 dm) {

        lbdiscomp3.setText("MP3");
        LNom.setText(dm.getNombre());
        LAutor.setText(dm.getAutorNombre());

        cargarImagen(dm.getImagen());

        mostrarComponentes();
        cargarCancionesEnTabla();
        cargarCancionesDelMp3(dm.getId_disco_mp3());
    }


    private void btnBuscarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVActionPerformed
        String idTexto = txtId.getText().trim();

        // ==== Validar campo vacío ====
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de disco.");
            return;
        }
        try {
            int id = Integer.parseInt(idTexto);

            Disco_viniloDAO dvD = new Disco_viniloDAO();
            Disco_vinilo dv = dvD.buscarPorIdV(id);

            // ============================
            //    1. NO EXISTE VINILO
            // ============================
            if (dv == null) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this, "No existe un disco con ese ID.");
                return;
            }

            // ============================
            //    2. VALIDAR QUE EL DISCO
            //       PERTENECE AL VENDEDOR
            // ============================
            int idUsuarioActual = Sesion.getIdVendedor();

            if (dv.getId_vendedor() != idUsuarioActual) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this,
                        "No puede modificar este disco porque pertenece a otro vendedor.");
                return;
            }

            // ============================
            //    3. MOSTRAR VINILO
            // ============================
            mostrarVinilo(dv);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
        }
    }//GEN-LAST:event_btnBuscarVActionPerformed

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        String idTexto = txtId.getText().trim();

        // ==== Validar campo vacío ====
        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de disco.");
            return;
        }
        try {
            int id = Integer.parseInt(idTexto);

            Disco_mp3DAO dmD = new Disco_mp3DAO();
            Disco_mp3 dm = dmD.buscarPorIM(id);

            // ============================
            //    1. NO EXISTE MP3
            // ============================
            if (dm == null) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this, "No existe un disco con ese ID.");
                return;
            }

            // ============================
            //    2. VALIDAR QUE EL DISCO
            //       PERTENECE AL VENDEDOR
            // ============================
            int idUsuarioActual = Sesion.getIdVendedor();

            if (dm.getId_vendedor() != idUsuarioActual) {
                imgDisco.setIcon(null);
                ocultarComponentes();
                JOptionPane.showMessageDialog(this,
                        "No puede modificar este disco porque pertenece a otro vendedor.");
                return;
            }

            // ============================
            //    3. MOSTRAR MP3
            // ============================
            mostrarMp3(dm);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
        }
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void btnBorrarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCancionActionPerformed
        // 1. Validar selección
        int index = jLista.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una canción de la lista.");
            return;
        }

        // 2. Obtener ID real de la canción desde el JList
        String textoCancion = jLista.getModel().getElementAt(index);
        int idCancion = Integer.parseInt(textoCancion.split(" - ")[0]); // ID es el primer valor

        // 3. Obtener ID del disco
        int idDisco = Integer.parseInt(txtId.getText().trim());

        // 4. Saber si es vinilo o mp3
        String tipo = lbdiscomp3.getText(); // VINILO o MP3

        boolean ok = false;

        // 5. Eliminar según tipo
        if (tipo.equalsIgnoreCase("VINILO")) {

            Cancion_viniloDAO cvDAO = new Cancion_viniloDAO();
            ok = cvDAO.eliminarCancionDeVinilo(idDisco, idCancion);

            if (ok) {
                cargarCancionesDelVinilo(idDisco);
            }

        } else if (tipo.equalsIgnoreCase("MP3")) {

            Cancion_disco_mp3DAO cmDAO = new Cancion_disco_mp3DAO();
            ok = cmDAO.eliminarCancionDeMp3(idDisco, idCancion);

            if (ok) {
                cargarCancionesDelMp3(idDisco);
            }
        }

        // 6. Mensaje final
        if (ok) {
            JOptionPane.showMessageDialog(this, "Canción eliminada correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar la canción.");
        }
    }//GEN-LAST:event_btnBorrarCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AsociarCanciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAutor;
    private javax.swing.JLabel LNom;
    private javax.swing.JButton btnAnadirCancion;
    private javax.swing.JButton btnBorrarCancion;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnBuscarV;
    private javax.swing.JLabel imgDisco;
    private javax.swing.JLabel imgSalir;
    private javax.swing.JList<String> jLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jlautor;
    private javax.swing.JLabel jlcan;
    private javax.swing.JLabel jlimagen;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor1;
    private javax.swing.JLabel lbdiscomp3;
    private javax.swing.JLabel lbtitulo2;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
