package Vista;

import Modelo.AutorDAO;
import Modelo.Cancion;
import Modelo.CancionDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class EditarCancion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCancion.class.getName());
    private int idCancionEditar;

    public EditarCancion(int idCancion) {
        initComponents();

        idCancionEditar = idCancion;

        // Primero cargar listas
        cargarArtistas();
        cargarDuracion();

        CancionDAO dao = new CancionDAO();
        Cancion c = dao.obtenerPorId(idCancion);

        if (c != null) {

            txtNombreCancion.setText(c.getNombre());
            txtGeneroCancion.setText(c.getGenero());
            txtTamanioCan.setText(String.valueOf(c.getTamano_mb()));
            txtCalidadCan.setText(String.valueOf(c.getCalidad_kbps()));
            txtPrecioCancion.setText(String.valueOf(c.getPrecio()));

            // Seleccionar artista
            cmbArtistaCan.setSelectedItem(c.getAutorNombre());

            // Seleccionar duración
            String dur = c.getDuracion();  // "03:25"
            if (dur != null && dur.contains(":")) {
                String[] partes = dur.split(":");
                String min = partes[0];
                String seg = partes[1];

                cmbMin.setSelectedItem(min);
                cmbSeg.setSelectedItem(seg);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la canción.");
        }
        
        // Cursor tipo mano en el label de salir
        imgSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Cursor tipo mano en los botones añadir artista
        btnAgregarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    private DefaultComboBoxModel<String> minutosModel = new DefaultComboBoxModel<>();
    private DefaultComboBoxModel<String> segundosModel = new DefaultComboBoxModel<>();

    private void cargarDuracion() {
        minutosModel.removeAllElements();
        segundosModel.removeAllElements();

        // Placeholder
        minutosModel.addElement("(minutos)");
        segundosModel.addElement("(segundos)");

        //Para minutos
        for (int i = 0; i <= 60; i++) {
            minutosModel.addElement(String.format("%02d", i));
        }
        //Para segundos
        for (int i = 0; i < 60; i++) {
            segundosModel.addElement(String.format("%02d", i));
        }

        cmbMin.setModel(minutosModel);
        cmbSeg.setModel(segundosModel);

        cmbMin.setSelectedIndex(0);
        cmbSeg.setSelectedIndex(0);
    }

    private void cargarArtistas() {
        AutorDAO dao = new AutorDAO();
        List<String> lista = dao.obtenerAutores();

        cmbArtistaCan.removeAllItems();

        for (String artista : lista) {
            cmbArtistaCan.addItem(artista);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbArtistaCan = new javax.swing.JComboBox<>();
        lbVendedor6 = new javax.swing.JLabel();
        lbVendedor11 = new javax.swing.JLabel();
        lbVendedor14 = new javax.swing.JLabel();
        txtNombreCancion = new javax.swing.JTextField();
        lbVendedor16 = new javax.swing.JLabel();
        txtGeneroCancion = new javax.swing.JTextField();
        lbVendedor12 = new javax.swing.JLabel();
        lbVendedor15 = new javax.swing.JLabel();
        lbVendedor13 = new javax.swing.JLabel();
        cmbMin = new javax.swing.JComboBox<>();
        cmbSeg = new javax.swing.JComboBox<>();
        txtTamanioCan = new javax.swing.JTextField();
        txtCalidadCan = new javax.swing.JTextField();
        txtPrecioCancion = new javax.swing.JTextField();
        lbVendedor17 = new javax.swing.JLabel();
        btnAgregarCancion = new javax.swing.JButton();
        imgSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        cmbArtistaCan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbArtistaCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbArtistaCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArtistaCanActionPerformed(evt);
            }
        });

        lbVendedor6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbVendedor6.setText("Editar canción (mp3)");

        lbVendedor11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor11.setText("Género");

        lbVendedor14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor14.setText("Duración");

        txtNombreCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbVendedor16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor16.setText("Nombe");

        txtGeneroCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbVendedor12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor12.setText("Artista");

        lbVendedor15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor15.setText("Tamaño (MB)");

        lbVendedor13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor13.setText("Calidad (Kbps)");

        cmbMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMinActionPerformed(evt);
            }
        });

        cmbSeg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSeg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSegActionPerformed(evt);
            }
        });

        txtTamanioCan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCalidadCan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPrecioCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbVendedor17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor17.setText("Precio");

        btnAgregarCancion.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar15px.png"))); // NOI18N
        btnAgregarCancion.setText("Editar canción");
        btnAgregarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCancionActionPerformed(evt);
            }
        });

        imgSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo salir.png"))); // NOI18N
        imgSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbVendedor12)
                            .addComponent(lbVendedor6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbVendedor15)
                                    .addComponent(lbVendedor14)
                                    .addComponent(lbVendedor11)
                                    .addComponent(lbVendedor16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTamanioCan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtGeneroCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(imgSalir)
                                        .addComponent(cmbArtistaCan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(402, 402, 402))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAgregarCancion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbVendedor17)
                                    .addGap(69, 69, 69)
                                    .addComponent(txtPrecioCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbVendedor13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCalidadCan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVendedor6)
                    .addComponent(imgSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVendedor16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor12)
                    .addComponent(cmbArtistaCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVendedor11)
                    .addComponent(txtGeneroCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor14)
                    .addComponent(cmbMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor15)
                    .addComponent(txtTamanioCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor13)
                    .addComponent(txtCalidadCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVendedor17))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarCancion)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbArtistaCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArtistaCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbArtistaCanActionPerformed

    private void cmbMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMinActionPerformed

    private void cmbSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSegActionPerformed

    private void btnAgregarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCancionActionPerformed
        String nombre = txtNombreCancion.getText().trim();
        String genero = txtGeneroCancion.getText().trim();
        String tamano = txtTamanioCan.getText().trim();
        String calidad = txtCalidadCan.getText().trim();
        String precio = txtPrecioCancion.getText().trim();

        String min = (String) cmbMin.getSelectedItem();
        String seg = (String) cmbSeg.getSelectedItem();
        String artista = (String) cmbArtistaCan.getSelectedItem();

        CancionDAO dao = new CancionDAO();
        Cancion original = dao.obtenerPorId(idCancionEditar);

        // 1. Validar que existe la canción
        if (original == null) {
            JOptionPane.showMessageDialog(this, "Error: la canción ya no existe.");
            return;
        }
        // 2. Validar campos vacíos
        if (nombre.isEmpty() || genero.isEmpty() || tamano.isEmpty() || calidad.isEmpty()
                || precio.isEmpty() || artista == null
                || min.equals("(minutos)") || seg.equals("(segundos)")) {

            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos.");
            return;
        }
        // 3. Validar números
        double tamanoVal;
        int calidadVal;
        double precioVal;

        try {
            tamanoVal = Double.parseDouble(tamano);
            calidadVal = Integer.parseInt(calidad);
            precioVal = Double.parseDouble(precio);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los campos de tamaño, calidad y precio deben ser numéricos.");
            return;
        }

        // 4. Construir la duración
        String duracion = min + ":" + seg;

        // 5. Verificar si NO hay cambios

        int idAutorNuevo = new AutorDAO().obtenerIdPorNombre(artista);

        boolean sinCambios
                = nombre.equals(original.getNombre())
                && genero.equals(original.getGenero())
                && tamanoVal == original.getTamano_mb()
                && calidadVal == original.getCalidad_kbps()
                && precioVal == original.getPrecio()
                && duracion.equals(original.getDuracion())
                && idAutorNuevo == original.getId_autor();

        if (sinCambios) {
            JOptionPane.showMessageDialog(this, "No hay cambios para guardar.");
            return;
        }

        // 6. Crear objeto modificado
        Cancion modificada = new Cancion();
        modificada.setId_cancion(idCancionEditar);
        modificada.setNombre(nombre);
        modificada.setGenero(genero);
        modificada.setTamano_mb(tamanoVal);
        modificada.setCalidad_kbps(calidadVal);
        modificada.setPrecio(precioVal);
        modificada.setDuracion(duracion);
        modificada.setId_autor(idAutorNuevo);
        modificada.setId_vendedor(original.getId_vendedor());

        // 7. Guardar cambios
        boolean ok = dao.modificarCancion(modificada);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Canción modificada correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar la canción.");
        }
    }//GEN-LAST:event_btnAgregarCancionActionPerformed

    private void imgSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalirMouseClicked

        Vendedor v = new Vendedor();
        v.setVisible(true);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        v.setResizable(false);
        dispose();
    }//GEN-LAST:event_imgSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new EditarCancion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCancion;
    private javax.swing.JComboBox<String> cmbArtistaCan;
    private javax.swing.JComboBox<String> cmbMin;
    private javax.swing.JComboBox<String> cmbSeg;
    private javax.swing.JLabel imgSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbVendedor11;
    private javax.swing.JLabel lbVendedor12;
    private javax.swing.JLabel lbVendedor13;
    private javax.swing.JLabel lbVendedor14;
    private javax.swing.JLabel lbVendedor15;
    private javax.swing.JLabel lbVendedor16;
    private javax.swing.JLabel lbVendedor17;
    private javax.swing.JLabel lbVendedor6;
    private javax.swing.JTextField txtCalidadCan;
    private javax.swing.JTextField txtGeneroCancion;
    private javax.swing.JTextField txtNombreCancion;
    private javax.swing.JTextField txtPrecioCancion;
    private javax.swing.JTextField txtTamanioCan;
    // End of variables declaration//GEN-END:variables
}
