package Vista.Vendedor;

import Modelo.CompradorDAO;
import Modelo.Detalle_venta;
import Modelo.Detalle_ventaDAO;
import Modelo.Venta;
import Modelo.VentaDAO;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class InfoPedido extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InfoPedido.class.getName());

    private int idVenta;
    private VentaDAO ventaDAO = new VentaDAO();
    private Detalle_ventaDAO detalleDAO = new Detalle_ventaDAO();
    private Vendedor vendedor;
    private CompradorDAO compradorDAO = new CompradorDAO();

    public InfoPedido(int idVenta, Vendedor vendedor) {
        this.idVenta = idVenta;
        this.vendedor = vendedor;
        initComponents();
        cargarDatosPedido();
        cargarProductos();

        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRechazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
    
        jTableProducto.setRowHeight(60);
        jTableProducto.setBackground(new java.awt.Color(89, 89, 89));
        jTableProducto.setGridColor(new java.awt.Color(89, 89, 89));
        jTableProducto.setSelectionBackground(new java.awt.Color(51, 51, 51));
        // Centrar datos en todas las columnas
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTableProducto.getColumnCount(); i++) {
            jTableProducto.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        
        // COLOR DE FONDO PARA EL HEADER (ya está en el código original, pero lo mantengo)
        javax.swing.table.JTableHeader header = jTableProducto.getTableHeader();
        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                jTableProducto.getTableHeader().setBackground(new java.awt.Color(89, 89, 89));
                jScrollPane1.getViewport().setBackground(new java.awt.Color(89, 89, 89));
                c.setBackground(new java.awt.Color(89, 89, 89));
                c.setForeground(Color.WHITE);
                setHorizontalAlignment(CENTER);
                return c;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbtexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbVendedor10 = new javax.swing.JLabel();
        lbVendedor11 = new javax.swing.JLabel();
        lbVendedor12 = new javax.swing.JLabel();
        lbVendedor13 = new javax.swing.JLabel();
        lbVendedor14 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbVendedor16 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();
        lbMetodo = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbComprador = new javax.swing.JLabel();
        lbPedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        lbtexto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbtexto.setText("Info del pedido");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        lbVendedor10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor10.setText("ID pedido:");

        lbVendedor11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor11.setText("Comprador:");

        lbVendedor12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor12.setText("Total:");

        lbVendedor13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor13.setText("Fecha:");

        lbVendedor14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor14.setText("Productos:");

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTotal.setText("txt");

        lbVendedor16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor16.setText("Método de pago:");

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cheque.png"))); // NOI18N
        btnAceptar.setText("Aceptar pedido");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rechazado.png"))); // NOI18N
        btnRechazar.setText("Rechazar pedido");
        btnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazarActionPerformed(evt);
            }
        });

        lbMetodo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMetodo.setText("txt");

        lbFecha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbFecha.setText("txt");

        lbComprador.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbComprador.setText("txt");

        lbPedido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbPedido.setText("txt");

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProducto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbtexto)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbVendedor12)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbTotal))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbVendedor10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbPedido))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbVendedor11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbComprador))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbVendedor13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbFecha))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbVendedor14)
                                            .addGap(74, 74, 74)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnAceptar)
                                .addGap(55, 55, 55)
                                .addComponent(btnRechazar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbVendedor16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbMetodo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor10)
                    .addComponent(lbPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor11)
                    .addComponent(lbComprador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor13)
                    .addComponent(lbFecha))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor16)
                    .addComponent(lbMetodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVendedor14)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor12)
                    .addComponent(lbTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnRechazar))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptarPedido();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        rechazarPedido();
    }//GEN-LAST:event_btnRechazarActionPerformed

    private void cargarDatosPedido() {
        Venta venta = ventaDAO.buscarPorIdVenta(idVenta);
        if (venta != null) {
            lbPedido.setText(String.valueOf(venta.getId_venta()));
            lbComprador.setText(compradorDAO.buscarPorId(venta.getId_comprador()).getNombre());
            lbFecha.setText(new SimpleDateFormat("dd/MM/yyyy").format(venta.getFecha()));
            lbMetodo.setText(venta.getMetodo_pago());
            lbTotal.setText(String.valueOf(venta.getTotal()));
        }
    }

    private void cargarProductos() {
        List<Detalle_venta> detalles = detalleDAO.listarDetallesPorVenta(idVenta);
        DefaultTableModel modelo = (DefaultTableModel) jTableProducto.getModel();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new String[]{"Tipo", "Producto", "Cantidad", "Precio Unit.", "Total"});

        for (Detalle_venta detalle : detalles) {
            modelo.addRow(new Object[]{
                detalle.getTipo(),
                "Producto ID: " + detalle.getId_producto(), // Ajusta si tienes nombre del producto
                detalle.getCantidad(),
                detalle.getPrecio_unit(),
                detalle.getTotal()
            });
        }
    }

    private void aceptarPedido() {
        List<Detalle_venta> detalles = detalleDAO.listarDetallesPorVenta(idVenta);
        boolean tieneVinilo = detalles.stream().anyMatch(d -> "vinilo".equalsIgnoreCase(d.getTipo()));

        Date fechaEntrega = null;
        if (tieneVinilo) {
            String fechaStr = JOptionPane.showInputDialog(this, "Ingrese fecha de entrega (dd/MM/yyyy o dd-MM-yyyy):");
            if (fechaStr == null || fechaStr.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una fecha para productos de vinilo.");
                return;
            }
            try {
                // Intentar parsear con formato dd/MM/yyyy primero
                SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
                sdf1.setLenient(false);  
                fechaEntrega = sdf1.parse(fechaStr.trim());
            } catch (Exception e1) {
                try {

                    SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy");
                    sdf2.setLenient(false);
                    fechaEntrega = sdf2.parse(fechaStr.trim());
                } catch (Exception e2) {
                    JOptionPane.showMessageDialog(this, "Fecha inválida. Use el formato dd/MM/yyyy o dd-MM-yyyy (ej: 24/12/2025 o 24-12-2025).");
                    return;
                }
            }

            Date hoy = new Date();
            if (fechaEntrega.before(hoy)) {
                JOptionPane.showMessageDialog(this, "La fecha de entrega no puede ser en el pasado.");
                return;
            }
        }

        // Actualizar estado a "aceptado"
        Venta venta = ventaDAO.buscarPorIdVenta(idVenta);
        venta.setEstado("aceptado");
        if (fechaEntrega != null) {
            venta.setObservacion("Fecha de entrega: " + new SimpleDateFormat("dd/MM/yyyy").format(fechaEntrega));
        }
        ventaDAO.modificarVenta(venta);

        // Incrementar compras del comprador
        compradorDAO.incrementarCompras(venta.getId_comprador());

        JOptionPane.showMessageDialog(this, "Pedido aceptado.");
        dispose();
        // Recargar la tabla de órdenes en Vendedor
        if (vendedor != null) {
            vendedor.cargarOrdenes();
        }
    }

    private void rechazarPedido() {
        List<Detalle_venta> detalles = detalleDAO.listarDetallesPorVenta(idVenta);
        boolean tieneVinilo = detalles.stream().anyMatch(d -> "vinilo".equalsIgnoreCase(d.getTipo()));

        String observacion = "";
        if (tieneVinilo) {
            observacion = JOptionPane.showInputDialog(this, "Ingrese observación para el rechazo:");
            if (observacion == null || observacion.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una observación para productos de vinilo.");
                return;
            }
        }

        // Actualizar estado a "rechazado" con observación
        Venta venta = ventaDAO.buscarPorIdVenta(idVenta);
        venta.setEstado("rechazado");
        venta.setObservacion(observacion);
        ventaDAO.modificarVenta(venta);

        JOptionPane.showMessageDialog(this, "Pedido rechazado.");
        dispose();

        if (vendedor != null) {
            vendedor.cargarOrdenes();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new InfoPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JLabel lbComprador;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbMetodo;
    private javax.swing.JLabel lbPedido;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbVendedor10;
    private javax.swing.JLabel lbVendedor11;
    private javax.swing.JLabel lbVendedor12;
    private javax.swing.JLabel lbVendedor13;
    private javax.swing.JLabel lbVendedor14;
    private javax.swing.JLabel lbVendedor16;
    private javax.swing.JLabel lbtexto;
    // End of variables declaration//GEN-END:variables
}
