package Vista.Comprador;

import Modelo.Lista_reproduccion;
import Modelo.Lista_reproduccionDAO;
import Modelo.Sesion;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */

public class CrearReco extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearReco.class.getName());

    private Comprador padre;
    public CrearReco(Comprador padre) {
        this.padre = padre;
        initComponents();
        btnCrearReco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ButtonGroup grupo = new ButtonGroup();
        grupo.add(rdbPublica);
        grupo.add(rdbPrivada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbVendedor1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbVendedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rdbPublica = new javax.swing.JRadioButton();
        rdbPrivada = new javax.swing.JRadioButton();
        btnCrearReco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        lbVendedor1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor1.setText("Nombre:");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbVendedor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbVendedor.setText("Crear Recopilación");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        rdbPublica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rdbPublica.setText("Pública");

        rdbPrivada.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rdbPrivada.setText("Pivada");

        btnCrearReco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo mas.png"))); // NOI18N
        btnCrearReco.setText("Crear");
        btnCrearReco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVendedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbVendedor1)
                        .addGap(32, 32, 32)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdbPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnCrearReco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVendedor)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVendedor1)
                    .addComponent(rdbPublica)
                    .addComponent(rdbPrivada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnCrearReco)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // Agrega esto en CrearReco.java (después del constructor existente):
     public CrearReco() {
         this(null);  // Llama al constructor con parámetro, pasando null
     }
     
    private void btnCrearRecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRecoActionPerformed
        // Validar que el nombre no esté vacío
        String nombre = txtId.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un nombre para la recopilación.");
            return;
        }
        // Validar que se haya seleccionado pública o privada
        String publica = null;
        if (rdbPublica.isSelected()) {
            publica = "Sí";  // O "true", dependiendo de cómo lo manejes en la BD
        } else if (rdbPrivada.isSelected()) {
            publica = "No";  // O "false"
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona si la recopilación es pública o privada.");
            return;
        }
        // Obtener id del comprador
        int idComprador = Sesion.getIdComprador();
        if (idComprador == 0) {
            JOptionPane.showMessageDialog(this, "Error: No hay un comprador logueado.");
            return;
        }
        // Obtener fecha de hoy
        String fechaCreacion = java.time.LocalDate.now().toString();
        // Crear objeto Lista_reproduccion
        Lista_reproduccion lista = new Lista_reproduccion();

        lista.setNombre(nombre);

        lista.setId_comprador(idComprador);

        lista.setPublica(publica);

        lista.setFecha_creacion(fechaCreacion);
        // Insertar en la base de datos
        Lista_reproduccionDAO dao = new Lista_reproduccionDAO();
        if (dao.insertarListaReproduccion(lista)) {
            JOptionPane.showMessageDialog(this, "Recopilación creada exitosamente.");
            // Actualizar la lista en la ventana padre (Comprador)
            if (padre != null) {
                padre.cargarListasReproduccion();  // Refresca la pestaña "Mis recopilaciones"
            }
            // Limpiar campos y cerrar ventana
            txtId.setText("");
            rdbPublica.setSelected(false);
            rdbPrivada.setSelected(false);
            this.dispose();  // Cerrar esta ventana
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear la recopilación.");
        }
    }//GEN-LAST:event_btnCrearRecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    //java.awt.EventQueue.invokeLater(() -> new CrearReco().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearReco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor1;
    private javax.swing.JRadioButton rdbPrivada;
    private javax.swing.JRadioButton rdbPublica;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
