package Vista.Comprador;

import Modelo.Cancion;
import Modelo.CancionDAO;
import Modelo.Canciones_listas;
import Modelo.Canciones_listasDAO;
import Modelo.Lista_reproduccion;
import Modelo.Lista_reproduccionDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class EditarReco extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarReco.class.getName());
    private int idLista;
    private List<Cancion> cancionesDisponibles;
    private List<Canciones_listas> cancionesEnListaActual;
    private Comprador padre;

    /**
     * Creates new form Recopilacion
     */
    public EditarReco(Comprador padre) {
        this.padre = padre;
        initComponents();
        cancionesEnListaActual = new ArrayList<>();

        btnAgregarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Agregar ButtonGroup para los radio buttons
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(rdbPublica);
        grupo.add(rdbPrivada);

        // Inicialmente deshabilitar botones
        btnAgregarCancion.setEnabled(false);
        btnEliminar.setEnabled(false);
        // Agregar listeners para selección en listas
        jLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                btnAgregarCancion.setEnabled(jLista.getSelectedIndex() != -1);
            }
        });
        jListaComprador.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                btnEliminar.setEnabled(jListaComprador.getSelectedIndex() != -1);
            }
        });

    }

    // En la clase EditarReco, agrega este constructor para recibir el padre
    public EditarReco(Comprador padre, int idLista, String nombre, String publica) {
        this(padre);  // Inicializa con padre
        this.idLista = idLista;

        // Setear valores
        txtNombre.setText(nombre);
        if ("Sí".equals(publica)) {
            rdbPublica.setSelected(true);
        } else {
            rdbPrivada.setSelected(true);
        }

        // Cargar canciones disponibles
        cargarCancionesDisponibles();

        // Cargar canciones de la lista actual
        cargarCancionesEnLista();
    }

    public EditarReco() {
        this(null);  // Llama al constructor con parámetro, pasando null
    }

    // Método para cargar canciones disponibles (todas las canciones)
    private void cargarCancionesDisponibles() {
        CancionDAO cancionDao = new CancionDAO();
        List<Cancion> canciones = cancionDao.listarTodas();
        System.out.println("cancionesDisponibles: " + cancionesDisponibles);
        if (cancionesDisponibles == null) {
            cancionesDisponibles = new ArrayList<>();  // Evita null
        }

        cancionesDisponibles = canciones;  // <-- Agrega esta línea
        DefaultListModel<String> modelo = new DefaultListModel<>();
        for (Cancion cancion : canciones) {
            // Mostrar nombre, autor y duración
            modelo.addElement(cancion.getNombre() + " - " + cancion.getAutorNombre() + " - " + cancion.getDuracion());
        }
        jLista.setModel(modelo);
    }

    // Método para cargar canciones en la lista actual
    private void cargarCancionesEnLista() {
        Canciones_listasDAO cancionesDao = new Canciones_listasDAO();
        List<Canciones_listas> cancionesEnLista = cancionesDao.listarCancionesPorLista(idLista);
        cancionesEnListaActual = cancionesEnLista;
        DefaultListModel<String> modelo = new DefaultListModel<>();
        CancionDAO cancionDao = new CancionDAO();
        for (Canciones_listas item : cancionesEnLista) {
            Cancion cancion = cancionDao.obtenerPorId(item.getId_cancion());
            if (cancion != null) {
                // Mostrar nombre, autor y duración
                modelo.addElement(cancion.getNombre() + " - " + cancion.getAutorNombre() + " - " + cancion.getDuracion());
            } else {
                modelo.addElement("Canción no encontrada (ID: " + item.getId_cancion() + ")");
            }
        }
        jListaComprador.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        btnEliminar = new javax.swing.JButton();
        lbVendedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbVendedor2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAgregarCancion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaComprador = new javax.swing.JList<>();
        lbreco = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        rdbPublica = new javax.swing.JRadioButton();
        rdbPrivada = new javax.swing.JRadioButton();
        lbVendedor3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        jLista.setBackground(new java.awt.Color(89, 89, 89));
        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jLista.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jLista);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar canción");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbVendedor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbVendedor.setText("Editar Recopilación");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        lbVendedor2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor2.setText("Canciones disponibles:");

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        btnAgregarCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo mas.png"))); // NOI18N
        btnAgregarCancion.setText("Agregar");
        btnAgregarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCancionActionPerformed(evt);
            }
        });

        jListaComprador.setBackground(new java.awt.Color(89, 89, 89));
        jListaComprador.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaComprador.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(jListaComprador);

        lbreco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbreco.setText("Mi recopilación:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        rdbPublica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rdbPublica.setText("Pública");

        rdbPrivada.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rdbPrivada.setText("Pivada");

        lbVendedor3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor3.setText("Canciones:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar.png"))); // NOI18N
        btnGuardar.setText("Guardar cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbVendedor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lbreco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdbPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdbPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbVendedor3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lbVendedor2))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVendedor)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbVendedor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbreco)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbPublica)
                            .addComponent(rdbPrivada)
                            .addComponent(btnGuardar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnAgregarCancion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbVendedor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(32, 32, 32)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCancionActionPerformed

        int selectedIndex = jLista.getSelectedIndex();
        if (selectedIndex != -1) {
            Cancion cancionSeleccionada = cancionesDisponibles.get(selectedIndex);

            // Recargar la lista actual desde la BD para asegurar datos frescos
            cargarCancionesEnLista();

            // Validación: Contar cuántas veces ya está la canción en la lista actual
            long count = cancionesEnListaActual.stream()
                    .filter(item -> item.getId_cancion() == cancionSeleccionada.getId_cancion())
                    .count();

            if (count >= 2) {
                JOptionPane.showMessageDialog(this, "No se puede agregar la misma canción más de dos veces a la recopilación.");
                return;  // No proceder con la inserción
            }

            // Proceder con la inserción si la validación pasa
            Canciones_listas nueva = new Canciones_listas();
            nueva.setId_lista(idLista);
            nueva.setId_cancion(cancionSeleccionada.getId_cancion());
            Canciones_listasDAO dao = new Canciones_listasDAO();
            if (dao.insertarCancionLista(nueva)) {
                JOptionPane.showMessageDialog(this, "Canción agregada exitosamente.");
                cargarCancionesEnLista(); // Recargar la lista de la recopilación
            } else {
                JOptionPane.showMessageDialog(this, "Error al agregar la canción.");
            }
        }
    }//GEN-LAST:event_btnAgregarCancionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Lista_reproduccionDAO dao = new Lista_reproduccionDAO();
        // Obtener los valores actuales de la lista desde la BD
        Lista_reproduccion listaActual = dao.buscarPorIdLista(idLista);
        if (listaActual == null) {
            JOptionPane.showMessageDialog(this, "Error: No se pudo obtener la lista actual.");
            return;
        }
        // Obtener los nuevos valores desde la UI
        String nuevoNombre = txtNombre.getText().trim();
        String nuevaPublica = rdbPublica.isSelected() ? "Sí" : "No";
        // Comparar con los valores actuales
        boolean nombreCambio = !nuevoNombre.equals(listaActual.getNombre());
        boolean publicaCambio = !nuevaPublica.equals(listaActual.getPublica());
        if (!nombreCambio && !publicaCambio) {
            JOptionPane.showMessageDialog(this, "No se han realizado cambios en la recopilación.");
            return;
        }
        // Hay cambios: proceder con la modificación
        Lista_reproduccion lista = new Lista_reproduccion();
        lista.setId_lista(idLista);
        lista.setNombre(nuevoNombre);
        lista.setPublica(nuevaPublica);
        if (dao.modificarListaReproduccion(lista)) {
            JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente.");

            // Refrescar la lista en la ventana padre (Comprador)
            if (padre != null) {
                padre.cargarListasReproduccion();
            }

            // Cerrar la ventana para que los cambios sean visibles
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar cambios.");
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int selectedIndex = jListaComprador.getSelectedIndex();
        if (selectedIndex != -1) {
            Canciones_listas cancionListaSeleccionada = cancionesEnListaActual.get(selectedIndex);
            Canciones_listasDAO dao = new Canciones_listasDAO();
            if (dao.eliminarCancionLista(cancionListaSeleccionada.getId_cancion_lista())) {
                JOptionPane.showMessageDialog(this, "Canción eliminada exitosamente.");
                cargarCancionesEnLista(); // Recargar la lista de la recopilación
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la canción.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarReco().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCancion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JList<String> jLista;
    private javax.swing.JList<String> jListaComprador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor2;
    private javax.swing.JLabel lbVendedor3;
    private javax.swing.JLabel lbreco;
    private javax.swing.JRadioButton rdbPrivada;
    private javax.swing.JRadioButton rdbPublica;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
