package Vista.Comprador;

import Modelo.Cancion;
import Modelo.Cancion_viniloDAO;
import Modelo.Carrito;
import Modelo.CarritoDAO;
import Modelo.Disco_vinilo;
import Modelo.Disco_viniloDAO;
import Modelo.Sesion;
import Modelo.VendedorDAO;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class InfoVinilo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InfoVinilo.class.getName());

    private int idVinilo;

    public InfoVinilo(int idVinilo) {
        this.idVinilo = idVinilo;
        initComponents();

        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Dejar el JList vacío
        jLista.setModel(new javax.swing.DefaultListModel<>());
        // Cargar datos del vinilo (labels e imagen)
        cargarDatosVinilo();

        // Cargar canciones
        cargarCancionesDelVinilo(idVinilo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbtitulo = new javax.swing.JLabel();
        lbVendedor2 = new javax.swing.JLabel();
        lbVendedor9 = new javax.swing.JLabel();
        lbVendedor5 = new javax.swing.JLabel();
        lbVendedor3 = new javax.swing.JLabel();
        imagenDisco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        lbVendedor4 = new javax.swing.JLabel();
        lbVendedor10 = new javax.swing.JLabel();
        lbArtista = new javax.swing.JLabel();
        lbAnio = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        lbVendedor11 = new javax.swing.JLabel();
        lbVendedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        lbtitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbtitulo.setText("Info del vinilo");

        lbVendedor2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor2.setText("Artista:");

        lbVendedor9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor9.setText("Género:");

        lbVendedor5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor5.setText("Año:");

        lbVendedor3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor3.setText("Canciones:");

        jLista.setBackground(new java.awt.Color(89, 89, 89));
        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jLista.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jLista);

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        lbVendedor4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor4.setText("Precio:");

        lbVendedor10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor10.setText("Nombre álbum:");

        lbArtista.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbArtista.setText("texto");

        lbAnio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbAnio.setText("texto");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbGenero.setText("texto");

        lbPrecio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPrecio.setText("texto");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNombre.setText("texto");

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carrito-de-compras.png"))); // NOI18N
        btnCarrito.setText("Agregar al carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        lbVendedor11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor11.setText("Vendedor:");

        lbVendedor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor.setText("texto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbVendedor4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbVendedor3)
                                                .addGap(57, 57, 57)))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbVendedor9)
                                    .addGap(67, 67, 67)
                                    .addComponent(lbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbVendedor10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbVendedor2)
                                    .addComponent(lbVendedor5))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(lbAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(imagenDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbtitulo)
                                .addGap(86, 86, 86)
                                .addComponent(lbVendedor11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtitulo)
                    .addComponent(lbVendedor11)
                    .addComponent(lbVendedor))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNombre)
                                .addComponent(lbVendedor10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbArtista)
                                    .addComponent(lbVendedor2))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGenero)
                            .addComponent(lbVendedor9))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAnio)
                            .addComponent(lbVendedor5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrecio)
                            .addComponent(lbVendedor4)))
                    .addComponent(imagenDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lbVendedor3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // Obtener el precio del vinilo cargado
        Disco_viniloDAO dao = new Disco_viniloDAO();
        Disco_vinilo v = dao.buscarPorIdV(idVinilo);
        if (v == null) {
            JOptionPane.showMessageDialog(this, "Error: No se pudo obtener la información del vinilo.");
            return;
        }

        // Pedir cantidad al usuario
        String cantidadStr = JOptionPane.showInputDialog(this, "Ingrese la cantidad deseada:", "Cantidad", JOptionPane.QUESTION_MESSAGE);
        if (cantidadStr == null || cantidadStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Operación cancelada.");
            return;
        }

        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadStr.trim());
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo mayor a 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para la cantidad.");
            return;
        }

        // Crear el objeto Carrito
        Carrito carrito = new Carrito();
        carrito.setId_comprador(Sesion.getIdComprador());
        carrito.setTipo("vinilo");
        carrito.setId_producto(idVinilo);
        carrito.setCantidad(cantidad);
        carrito.setPrecio_unitario(v.getPrecio());
        carrito.setFecha_agregado(new java.sql.Date(System.currentTimeMillis()));
        carrito.setEstado("activo");

        // Agregar el id_vendedor capturado desde el vinilo
        carrito.setId_vendedor(v.getId_vendedor());

        // Agregar al carrito usando el DAO
        CarritoDAO carritoDAO = new CarritoDAO();
        boolean agregado = carritoDAO.agregarItemCarrito(carrito);

        if (agregado) {
            JOptionPane.showMessageDialog(this, "Vinilo agregado al carrito exitosamente.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el vinilo al carrito.");
        }
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void cargarCancionesDelVinilo(int idVinilo) {
        Cancion_viniloDAO cavD = new Cancion_viniloDAO();
        List<Cancion> lista = cavD.listarCancionesPorVinilo(idVinilo);

        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();

        for (Cancion c : lista) {
            modelo.addElement(
                    c.getId_cancion() + " - " + c.getNombre() + " - " + c.getDuracion()
            );
        }

        jLista.setModel(modelo);
    }


    private void cargarDatosVinilo() {
        Disco_viniloDAO dao = new Disco_viniloDAO();
        Disco_vinilo v = dao.buscarPorIdV(idVinilo);
        if (v == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el vinilo.");
            return;
        }
        // Obtener y setear los labels con los datos del vinilo
        lbNombre.setText(v.getNombre());
        lbGenero.setText(v.getGenero());
        lbAnio.setText(String.valueOf(v.getAnio_salida()));
        lbPrecio.setText("$" + String.valueOf(v.getPrecio()));  // Agregado: formato con $
        lbArtista.setText(v.getAutorNombre());

        // Obtener el nombre del vendedor
        VendedorDAO vendedorDAO = new VendedorDAO();
        Modelo.Vendedor vendedor = vendedorDAO.buscarPorId(v.getId_vendedor());
        if (vendedor != null) {
            lbVendedor.setText(vendedor.getNombre());
        } else {
            lbVendedor.setText("Desconocido");
        }

        // Obtener y setear la imagen del disco
        if (v.getImagen() != null) {
            // Si hay imagen en la BD, cargarla y escalarla
            ImageIcon icono = new ImageIcon(v.getImagen());
            Image img = icono.getImage().getScaledInstance(
                    imagenDisco.getWidth(),
                    imagenDisco.getHeight(),
                    Image.SCALE_SMOOTH
            );
            imagenDisco.setIcon(new ImageIcon(img));
        } else {
            // Si no hay imagen, asignar la por defecto en src/Img/disco.png
            try {
                ImageIcon iconoDefecto = new ImageIcon(getClass().getResource("/Img/disco.png"));
                Image img = iconoDefecto.getImage().getScaledInstance(
                        imagenDisco.getWidth(),
                        imagenDisco.getHeight(),
                        Image.SCALE_SMOOTH
                );
                imagenDisco.setIcon(new ImageIcon(img));
            } catch (Exception e) {
                // Si falla la carga de la imagen por defecto, mostrar texto
                imagenDisco.setText("Imagen no disponible");
            }
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new InfoVinilo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JLabel imagenDisco;
    private javax.swing.JList<String> jLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAnio;
    private javax.swing.JLabel lbArtista;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor10;
    private javax.swing.JLabel lbVendedor11;
    private javax.swing.JLabel lbVendedor2;
    private javax.swing.JLabel lbVendedor3;
    private javax.swing.JLabel lbVendedor4;
    private javax.swing.JLabel lbVendedor5;
    private javax.swing.JLabel lbVendedor9;
    private javax.swing.JLabel lbtitulo;
    // End of variables declaration//GEN-END:variables
}
