package Vista.Comprador;

import Modelo.Cancion;
import Modelo.CancionDAO;
import Modelo.Carrito;
import Modelo.CarritoDAO;
import Modelo.Sesion;
import java.awt.Image;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

public class InfoCancion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InfoCancion.class.getName());

    private int idCancion;

    public InfoCancion(int idCancion) {
        this.idCancion = idCancion;
        initComponents();

        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Cargar datos del vinilo (labels e imagen)
        cargarDatosCancion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbVendedor = new javax.swing.JLabel();
        lbVendedor2 = new javax.swing.JLabel();
        lbVendedor9 = new javax.swing.JLabel();
        lbVendedor5 = new javax.swing.JLabel();
        imagenDisco = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbVendedor4 = new javax.swing.JLabel();
        lbVendedor10 = new javax.swing.JLabel();
        lbArtista = new javax.swing.JLabel();
        lbDuracion = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        btnReco = new javax.swing.JButton();
        lbVendedor6 = new javax.swing.JLabel();
        lbVendedor7 = new javax.swing.JLabel();
        lbCalidad = new javax.swing.JLabel();
        lbTamanio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        lbVendedor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbVendedor.setText("Info de la canción");

        lbVendedor2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor2.setText("Artista:");

        lbVendedor9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor9.setText("Género:");

        lbVendedor5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor5.setText("Tamaño (MB):");

        imagenDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo musica grande.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        lbVendedor4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor4.setText("Precio:");

        lbVendedor10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor10.setText("Nombre:");

        lbArtista.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbArtista.setText("texto");

        lbDuracion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDuracion.setText("texto");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbGenero.setText("texto");

        lbPrecio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPrecio.setText("texto");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNombre.setText("texto");

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carrito-de-compras.png"))); // NOI18N
        btnCarrito.setText("Agregar al carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnReco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/musica.png"))); // NOI18N
        btnReco.setText("Agregar a recopilacion");

        lbVendedor6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor6.setText("Duración:");

        lbVendedor7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbVendedor7.setText("Calidad (Kbps):");

        lbCalidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbCalidad.setText("texto");

        lbTamanio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbTamanio.setText("texto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbVendedor9)
                                    .addGap(67, 67, 67)
                                    .addComponent(lbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbVendedor10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbVendedor2)
                                        .addComponent(lbVendedor6))
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVendedor5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(imagenDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbVendedor)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVendedor7)
                                .addGap(18, 18, 18)
                                .addComponent(lbCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVendedor4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReco, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVendedor)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVendedor10)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbArtista)
                                    .addComponent(lbVendedor2))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGenero)
                            .addComponent(lbVendedor9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVendedor6)
                            .addComponent(lbDuracion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVendedor5)
                            .addComponent(lbTamanio))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedor7)
                    .addComponent(lbCalidad)
                    .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbVendedor4)
                        .addComponent(lbPrecio)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed

        CancionDAO dao = new CancionDAO();
        Cancion c = dao.obtenerPorId(idCancion);
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Error: No se pudo obtener la información del mp3.");
            return;
        }
        // Crear el objeto Carrito
        Carrito carrito = new Carrito();
        carrito.setId_comprador(Sesion.getIdComprador());
        carrito.setTipo("Canción");
        carrito.setId_producto(idCancion);
        carrito.setPrecio_unitario(c.getPrecio());
        carrito.setCantidad(1);
        carrito.setFecha_agregado(new java.sql.Date(System.currentTimeMillis()));
        carrito.setEstado("activo");

        // Agregar el id_vendedor capturado desde el vinilo
        carrito.setId_vendedor(c.getId_vendedor());

        // Agregar al carrito usando el DAO
        CarritoDAO carritoDAO = new CarritoDAO();
        boolean agregado = carritoDAO.agregarItemCarrito(carrito);

        if (agregado) {
            JOptionPane.showMessageDialog(this, "Canción agregada al carrito exitosamente.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar la Canción al carrito.");
        }
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void cargarDatosCancion() {
        CancionDAO dao = new CancionDAO();
        Cancion c = dao.obtenerPorId(idCancion);
        if (c == null) {
            JOptionPane.showMessageDialog(this, "No se encontró la canción.");
            return;
        }
        lbNombre.setText(c.getNombre());
        lbArtista.setText(c.getAutorNombre());
        lbGenero.setText(c.getGenero());
        lbDuracion.setText(c.getDuracion());
        lbTamanio.setText(String.valueOf(c.getTamano_mb()));
        lbCalidad.setText(String.valueOf(c.getCalidad_kbps()));
        lbPrecio.setText("$" + String.valueOf(c.getPrecio()));

        ImageIcon iconoActual = (ImageIcon) imagenDisco.getIcon();
        Image img = iconoActual.getImage().getScaledInstance(
                166, // Ancho fijo
                166, // Alto fijo
                Image.SCALE_SMOOTH
        );
        imagenDisco.setIcon(new ImageIcon(img));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new InfoVinilo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnReco;
    private javax.swing.JLabel imagenDisco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbArtista;
    private javax.swing.JLabel lbCalidad;
    private javax.swing.JLabel lbDuracion;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbTamanio;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor10;
    private javax.swing.JLabel lbVendedor2;
    private javax.swing.JLabel lbVendedor4;
    private javax.swing.JLabel lbVendedor5;
    private javax.swing.JLabel lbVendedor6;
    private javax.swing.JLabel lbVendedor7;
    private javax.swing.JLabel lbVendedor9;
    // End of variables declaration//GEN-END:variables
}
